### ISSUE TITLE
如何使用 看不明白

### ISSUE THREAD

**Issue by jakesparro** [Haoyi-Han/Moxmoe-Epub-Manga-Repacker#14]

**Comment by Haoyi-Han** [comment]
使用步骤：
- 将你想要转换的漫画 EPUB 文档或包含这些文档的文件夹复制到同一个目录下。
- 克隆本项目或直接下载可执行程序。
- 在 `config.toml` 配置文件中修改输入目录为你要转换的漫画文档所在目录，修改输出目录和缓存目录为你想要的任意目录。
- 如果你使用 Python 运行代码而非直接运行程序，你需要使用 `poetry` 安装必要的依赖。
  - 在项目目录下运行 `poetry install` 安装依赖，之后运行 Python 时使用 `poetry run python` 替代 `python`。
  - 如果你不希望使用 `poetry`，可以打开 `pyproject.toml`，手动安装 `[tool.poetry.dependencies]` 和 `[tool.poetry.group.dev.dependencies]` 中记录的各项依赖。
- 用 Python 运行 `main.py` 或直接运行程序即可等待转换完成。
