### ISSUE TITLE
作者你好, 好像提取失败了

### ISSUE THREAD

**Issue by mcwq123** [Haoyi-Han/Moxmoe-Epub-Manga-Repacker#2]
![image](https://user-images.githubusercontent.com/73888233/209521014-6e64e370-cc58-437c-8291-3b1189596759.png)
不知道是什么原因提取失败了

**Comment by Haoyi-Han** [comment]
我是在 Windows 环境下开发的，Mac 中的 `._` 信息文件暂时没有考虑到。现阶段建议你先移除目录中的所有 `._` 文件后再试，应该可以解决问题。

dot clean 参考：[How to prevent MacOS from adding dot underscore files (._whatever.html )in zip archives?](https://apple.stackexchange.com/questions/414947/how-to-prevent-macos-from-adding-dot-underscore-files-whatever-html-in-zip-a)

以后的版本可能会考虑过滤这部分文件。

**Comment by Haoyi-Han** [comment]
代码已修复，可以尝试最新版本的代码。

**Comment by mcwq123** [comment]
感谢作者! 已经能完美提取了, 提取打包非常快速!
