### ISSUE TITLE
作者你好, 最近在Mox下载的漫画提取问题? AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by mcwq123** [Haoyi-Han/Moxmoe-Epub-Manga-Repacker#3]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/73888233/219048912-b597cd55-4eb3-4d50-a6eb-085d3c540a97.png">
以前的漫画文件尝试了提取是正常的, 这个是最近下载的, 不知道出现了是什么问题, 谢谢作者的辛苦工作了!

问题报告: 
`Last login: Wed Feb 15 22:00:26 on ttys001
wq@192 夫妻甜蜜物语 % python3 MoeKepub2Cbz.py
============> 开始初始化程序
已完成文件列表抽取。
输入目录为： /Volumes/HDD/Comic/夫妻甜蜜物语
输出目录为： /Volumes/HDD/Comic/夫妻甜蜜物语/output
已完成目录结构复制。
============> 开始提取图片并打包文件
Mox.moe |⚠︎                                       | (!) 0/180 [0%] in 0.1s (0.00/
Traceback (most recent call last):
  File "/Volumes/HDD/Comic/夫妻甜蜜物语/MoeKepub2Cbz.py", line 139, in <module>
    bar.text = comicNameExtract(file_t)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/HDD/Comic/夫妻甜蜜物语/MoeKepub2Cbz.py", line 57, in comicNameExtract
    return re.search(r'(\[Mox.moe\]|\[Mox\])(.+?)\.+?', str(comic_file.stem)).group(2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
wq@192 夫妻甜蜜物语 % 
`

**Comment by Haoyi-Han** [comment]
请问你是否下载漫画文档后改过文件名？或者方便的话，请展示一下程序所在的目录下的文件树，谢谢~
（P.S. 此漫画在我这边经测试能正常转换）

**Comment by mcwq123** [comment]
好的, Haoyi-Han大大, 我下载漫画文档后没有修改文件名
这是我的文件树和根目录截图: 
<img width="226" alt="image" src="https://user-images.githubusercontent.com/73888233/219053531-5adc3a08-9a0f-4cac-81c0-33a45b67670e.png">
![2023-02-15_22-27-25](https://user-images.githubusercontent.com/73888233/219055581-ace3ee3c-19f8-4bca-b08e-3753b659dec0.jpg)

**Comment by Haoyi-Han** [comment]
看来是官网这两天又改名了（我今天上午看到的还是 Mox），请将所有文件名中的 [Kox] 改为 [Mox] 再运行程序即可正常转换，晚些时候我会更新程序，兼容这一新变化。

**Comment by mcwq123** [comment]
原来如此, 刚才修改了成[Mox]之后就提取成功了, 谢谢Haoyi-Han大大的耐心解答, 祝您工作顺利!

**Comment by Haoyi-Han** [comment]
谢谢！祝好！
