### ISSUE TITLE
新版本无法进行转换

### ISSUE THREAD

**Issue by asddaasdda** [Haoyi-Han/Moxmoe-Epub-Manga-Repacker#8]
你好，使用新版时，双击exe文件后会短暂跳出一个窗口随后自动关闭，不会对文件进行转换。
旧版本却没有这个问题。

**Comment by Haoyi-Han** [comment]
我这边经检验是能正常工作的。请问你在使用前，是否更改了 `config.conf` 中的参数？现在的版本为防止符号链接带来的问题，已经不再支持默认转换当前目录，而是需要在该文件中手动指定转换的输入输出目录。（`README` 中似乎没有改相关说明，之后会修正）

**Comment by Haoyi-Han** [comment]
如果更改后仍然发生该问题，可以的话希望能提供一下你的目录结构（包括待转换文件和程序文件），方便诊断问题。

**Comment by asddaasdda** [comment]
你好，
已经尝试修改config文件，问题依旧存在。
文件夹结构大致如下，
- Manga
  - TEST
    - input
      - cache
    - output

相应的文件放在下面，
https://wwtp.lanzoul.com/ihPDQ0y3x84d
密码:hhbq
感谢;)

**Comment by Haoyi-Han** [comment]
程序已经重新打包，我这边经检验未发现问题，请您尝试验证一下：
[分享链接](https://wormhole.app/7xjxn#z4g4F1Yp1hMJirmLGeu8cw)（有效期 24 小时）
另外请注意将 `config.conf` 修改保存时使用 UTF-8 格式（无 BOM）。
您这边的运行结果（正常或依然存在问题）希望反馈一下，如果正常的话我之后会替换 Release 里的程序文件，感谢您的帮助。

**Comment by asddaasdda** [comment]
可以正常运行了，感谢。
